# Website details
name : Thulasi
tagline : Minimal Jekyll Blog Template 
description: "A snapshot of my life. Blogs about places I visit, topics I learn, things I love and experiences I earn."
#avatar : https://raw.githubusercontent.com/guyswhocode/guyswhocode.github.io/master/guyswhocode-logo.png
author : Shajan Jacob

#lighter
color-1 : 3BB874
#darker 
color-2 : 4D4F53

# Jekyll
paginate: 10
gems: [jekyll-paginate]
paginateLabel: page
paginate_path: "page/:num"
permalink: /:title
baseurl: http://shajanjacob.com/thulasi
url: http://shajanjacob.com

highlighter: rouge

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: shajanjp@gmail.com
  facebook: shajanjp
  flickr:
  github: shajanjp
  instagram: shajanjp
  linkedin: shajanjp
  pinterest: shajanjp
  rss: # just type anything here for a working RSS icon
  twitter: shajanjacob
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: shajanjp

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# The release of Jekyll Now that you're using
version: v1.2.0
